"""deleted Product table

Revision ID: b80f972c5722
Revises: ed56919404d4
Create Date: 2021-08-29 19:28:49.663967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b80f972c5722'
down_revision = 'ed56919404d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_type', mysql.ENUM('PLANTER', 'RAISED_BED', 'OTHER', collation='utf8_bin'), nullable=True),
    sa.Column('width', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('height', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('leg_height', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('with_legs', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('length', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('(`with_legs` in (0,1))', name='product_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
