"""changed field names in Product

Revision ID: ed56919404d4
Revises: 59183c989e98
Create Date: 2021-08-29 12:17:44.108758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed56919404d4'
down_revision = '59183c989e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('product', 'depth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('depth', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('product', 'length')
    # ### end Alembic commands ###
